Gorina/3171 owner tab on system detail
bcvsolutions/CzechIdMng pull request #261
Opened 2022-09-07 11:23 UTC by EvgeniyaGorina

https://redmine.czechidm.com/issues/3171

2022-09-14 12:49 UTC, kucera-roman requested changes
I did code review. I have few comments, but all minor things. Please look at it. If you need more information about something feel free to ask me.

SystemOwnerManager, SystemOwnerRoleManager should be under redux folder (update index.js then)
SystemOwnerService, SystemOwnerRoleService should be under services folder  (update index.js then)

In the mean time I will test it in GUI.

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemOptionDecorator.js
> + * @author Radek Tomiška
Wrong doc - author and since

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemSelect.js
> +          LOGGER.warn(`IdentitySelect supports identity entity type only, given [${ entityType }] type will be ignored.`);
Should be SystemSelect supports system entity?

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemValueDecorator.js
> + * @author Radek Tomiška
Wrong doc - author and since

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/locales/cs.json
> +        "label": "Vlastík - identita",
Should be "Vlastník"

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +import EntityManager from 'czechidm-core/src/redux/data/EntityManager';
It's defined in core module, there is no need to define it also in acc

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +import IdentityManager from 'czechidm-core/src/redux/data/IdentityManager';
It's defined in core module, there is no need to define it also in acc

2022-09-14 12:49 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/module-descriptor.js
> +                access: [ { type: 'HAS_ALL_AUTHORITIES', authorities: ['SYSTEM_READ', 'ACCOUNT_READ'] } ]
Authorities should be SYSTEMOWNER_READ and SYSTEMOWNERROLE_READ

2022-09-19 09:09 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-app/src/store.js
> +// const store = createStoreWithMiddleware(reducer);
done

2022-09-19 09:09 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/services/ScriptService.js
> +    return true;
done

2022-09-19 09:10 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-app/src/store.js
> +const store = createStoreWithMiddleware(reducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());
done

2022-09-19 09:10 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/routes.js
> +          access: [ { type: 'HAS_ALL_AUTHORITIES', authorities: ['SYSTEM_READ', 'ACCOUNT_READ'] } ]
done

2022-09-19 09:13 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/services/ScriptService.js
> +    return true;
done

2022-09-19 09:14 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/services/ScriptService.js
> +    return false;
done

2022-09-19 09:19 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +import EntityManager from 'czechidm-core/src/redux/data/EntityManager';
done

2022-09-19 09:19 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/locales/cs.json
> +        "label": "Vlastík - identita",
done

2022-09-19 10:22 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemValueDecorator.js
> + * @author Radek Tomiška
done

2022-09-19 10:22 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemOptionDecorator.js
> + * @author Radek Tomiška
done

2022-09-19 10:31 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemSelect.js
> +          LOGGER.warn(`IdentitySelect supports identity entity type only, given [${ entityType }] type will be ignored.`);
done

2022-09-19 10:31 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemOptionDecorator.js
> + * @author Radek Tomiška
done

2022-09-19 10:32 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/components/SystemSelect/SystemValueDecorator.js
> + * @author Radek Tomiška
done

2022-09-19 10:42 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +import IdentityManager from 'czechidm-core/src/redux/data/IdentityManager';
done

2022-09-28 08:11 UTC, kucera-roman requested changes
Almost everything was fixed, thx.
There are still some things to fix, please look at the comments.

Also please add localization for permissions, you can done this in localization files in acc module on line 1866

Last thing is to add green pop up message when new owner is added. (same pop up message is displayed if you delete some owner)

2022-09-29 07:39 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +
Done

2022-09-29 07:40 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/src/redux/index.js
> +
done

2022-09-29 07:40 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/identity/IdentityTable.js
> +            // href={ ({ rowIndex, data }) => {
done

2022-09-29 07:45 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/routes.js
> +          access: [ { type: 'HAS_ALL_AUTHORITIES', authorities: ['SYSTEMOWNER_READ', 'SYSTEMOWNERROLE_READ'] } ]
done

2022-09-29 09:29 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/identity/IdentityTable.js
> +            // href={ ({ rowIndex, data }) => {
Already I have it back

2022-09-29 09:36 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-acc/module-descriptor.js
> +                access: [ { type: 'HAS_ALL_AUTHORITIES', authorities: ['SYSTEM_READ', 'ACCOUNT_READ'] } ]
done

2022-09-30 08:11 UTC, kucera-roman approved these changes
LGTM

2022-09-30 08:14 UTC, merged