Doischer/2491 implement search for scripts in mapping
bcvsolutions/CzechIdMng pull request #266
Opened 2022-09-15 10:56 UTC by tomdoischer

https://redmine.czechidm.com/issues/2491

2022-09-28 08:30 UTC, kucera-roman requested changes
LGTM, working nicely. Fix just one small thing.

2022-09-28 08:30 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/services/SystemAttributeMappingService.js
> +    // .get(`/script-usage/${ encodeURIComponent(code) }`)
remove commented code please.

2022-09-29 06:15 UTC, tomdoischer commented on Realization/frontend/czechidm-acc/src/services/SystemAttributeMappingService.js
> +    // .get(`/script-usage/${ encodeURIComponent(code) }`)
Thanks, done. :)

2022-09-29 06:42 UTC, kucera-roman approved these changes
LGTM

2022-09-29 06:43 UTC, merged