Gorina/3192 role criticality and description display in role request dashboard width
bcvsolutions/CzechIdMng pull request #268
Opened 2022-09-26 09:22 UTC by EvgeniyaGorina

https://redmine.czechidm.com/issues/3192

2022-09-27 12:38 UTC, tomdoischer requested changes
Just minor notes.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/identity/IdentityRoleTable.js
> +          columns={_columns}
The spaces should be there.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +            cell={ ({ rowIndex, data }) => data[rowIndex]._embedded.role.priority }/>
Please, format this the same way other columns are.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/role/RoleFormAttributes.js
> +          <Basic.ContentHeader icon="fa:th-list" text={ this.i18n('content.role.formAttributes.header') } style={{marginBottom: 0 }}/>
The space should be there.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/locales/cs.json
>          "result": {
This file shouldn't be changed at all.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/locales/en.json
>          "result": {
This file shouldn't be changed at all.

2022-09-27 12:38 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/css/main.less
> +  }
The code formatting is wrong in ".advanced-tree".

In my opinion, this should not be placed in main.less but in a more specific less file (Table.less seems ideal).

2022-09-27 13:40 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/identity/IdentityRoleTable.js
> +          columns={_columns}
done

2022-09-27 13:56 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +            cell={ ({ rowIndex, data }) => data[rowIndex]._embedded.role.priority }/>
done

2022-09-27 13:56 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/role/RoleFormAttributes.js
> +          <Basic.ContentHeader icon="fa:th-list" text={ this.i18n('content.role.formAttributes.header') } style={{marginBottom: 0 }}/>
done

2022-09-27 13:58 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/locales/cs.json
>          "result": {
done

2022-09-27 14:00 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/locales/en.json
>          "result": {
done

2022-09-27 14:02 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/css/main.less
> +  }
Doesn't work from other less, I have try it but visible for components those styles only from main, have no idea why

2022-10-10 07:28 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +      'idm.pub.app.show.RequestIdentityRoleTable.table.columns',
I suggest the configuration key be: idm.pub.app.show.role.request.table.columns

2022-10-10 07:30 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/css/RoleTable.less
> +//Wide of columns in role and description and priority
This is not the right location for the file. This file should be in Realization/frontend/czechidm-core/src/content/role

2022-10-10 07:32 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +  columns: ConfigLoader.getConfig('RequestIdentityRoleTable.table.columns', [
This should be 'role.request.table.columns'

2022-10-10 07:37 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +    'role.name',
This should just be 'name', you will need to change the column use a little bit (basically the same way you did for priority and description).

The same for the examples below:
'_embedded.role.baseCode', -> baseCode
'_embedded.role.environment', -> environment

2022-10-10 07:48 UTC, tomdoischer requested changes
I have minor notes. Also, please edit the following file

/idm-app/src/main/resources/application.properties

and add the default configuration of columns for the role request table in the same way that 
"idm.pub.app.show.role.table.columns=name, baseCode, environment, disabled, description" is used.

2022-10-10 08:26 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +      'idm.pub.app.show.RequestIdentityRoleTable.table.columns',
done

2022-10-10 11:33 UTC, EvgeniyaGorina commented on Realization/frontend/czechidm-core/src/css/RoleTable.less
> +//Wide of columns in role and description and priority
done

2022-10-11 12:44 UTC, tomdoischer commented on Realization/backend/app/src/main/resources/application.properties
> +# - action
The default is great, just please add "action" to the end. It is now missing and users cannot remove roles.

2022-10-11 13:00 UTC, tomdoischer commented on Realization/backend/app/src/main/resources/application.properties
> +# Rendered column in role table agenda. Comma is used as separator. Order of rendered columns is preserved as configured.
"Rendered column in role table agenda." should be "Rendered columns in role request table agenda."

2022-10-12 07:25 UTC, tomdoischer approved these changes
Looks good to me!

2022-10-18 11:36 UTC, merged