Kucerar/3150 other account request
bcvsolutions/CzechIdMng pull request #269
Opened 2022-09-26 12:13 UTC by kucera-roman

2022-10-19 08:43 UTC, tomdoischer requested changes
The code looks good, minor things in the comments.

During testing, I found that:

- for other personal accounts, the identity account is not created
- the account agenda doesn't show the system entity for some reason for accounts created in the wizard
- [minor, can ignore] if I create an account with a uid that is already used, I get a pretty generic error message, I would like to know that the uid is used

2022-10-19 08:43 UTC, tomdoischer commented on Realization/frontend/czechidm-acc/src/content/wizard/AccountWizardDetail.js
> +  reopened: false // Defines if the wizard use for create new system or for reopen existed.
account instead of system in the comment

2022-10-19 11:57 UTC, kucera-roman commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/rest/impl/AccAccountController.java
> +		return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
fixed

2022-10-19 11:57 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/content/wizard/AccountWizardDetail.js
> +  reopened: false // Defines if the wizard use for create new system or for reopen existed.
fixed

2022-10-20 05:31 UTC, kucera-roman commented
I added new exception if no login is found.
This will prevent issue when broken account could be created.

For account created via wizard I can see everything in account agenda. We can look at it together

2022-11-01 12:30 UTC, tomdoischer commented
Looks good to me!

2022-11-01 12:31 UTC, merged