Kucerar/3164 account detail
bcvsolutions/CzechIdMng pull request #272
Opened 2022-10-13 08:43 UTC by kucera-roman

https://redmine.czechidm.com/issues/3164

2022-10-19 13:15 UTC, tomdoischer requested changes
Notes from testing

- on the provisioning detail for an account, active provisioning bulk actions do not work - doesn't always happen, see the console.log in the attached file
[log.txt](https://github.com/bcvsolutions/CzechIdMng/files/9820782/log.txt)
- provisioning detail for other accounts does not work correctly - requests are shown for different accounts
-  issue with overriding values with multiple provisioning mappings: DefaultSysSystemMappingService:425 - using the first provisioning mapping
- account detail - make the field for lines longer or dynamic - see the screenshot for a very long value - most of the page is empty and I have to scroll
- mapping and attribute override - if an attribute is removed from the mapping without account resave from the identity, the attribute is still seen on the account detail and will never disappear

2022-10-19 13:15 UTC, tomdoischer commented on Realization/frontend/czechidm-acc/src/locales/cs.json
> +          "help": "Vyplňte atributy účtu. Hodnoty mohou být předvyplněny navrhovanými hodnotami. Pokud je to dovoleno, hodnoty mohou být ručně upraveny.",
The if part is not accurate, it is always allowed right now I think.

2022-10-19 13:15 UTC, tomdoischer commented on Realization/frontend/czechidm-acc/src/locales/en.json
> +          "help": "Fill attributes for account. Values could be filled with suggested values. If it's allowed, you can change them manually.",
The if part is not accurate, it is always allowed right now I think.

2022-10-20 08:45 UTC, kucera-roman commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/event/processor/AccountProvisioningProcessor.java
> +public class AccountProvisioningProcessor extends CoreEventProcessor<IdmFormInstanceDto> {
fixed

2022-10-20 08:47 UTC, kucera-roman commented
Fixing review notes
> Notes from testing
> 
> * on the provisioning detail for an account, active provisioning bulk actions do not work - doesn't always happen, see the console.log in the attached file
>   [log.txt](https://github.com/bcvsolutions/CzechIdMng/files/9820782/log.txt)
> * provisioning detail for other accounts does not work correctly - requests are shown for different accounts
> * ~~issue with overriding values with multiple provisioning mappings: DefaultSysSystemMappingService:425 - using the first provisioning mapping~~
> * account detail - make the field for lines longer or dynamic - see the screenshot for a very long value - most of the page is empty and I have to scroll
> * mapping and attribute override - if an attribute is removed from the mapping without account resave from the identity, the attribute is still seen on the account detail and will never disappear
> * ~~cannot create a new account via wizard because the AccountProvisioningProcessor catches it tries to do a provisioning without system entity~~

2022-10-20 09:09 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/module-descriptor.js
> +            id: 'account-other',
fixed, renamed id, renamed class

2022-10-20 10:22 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/locales/cs.json
> +          "help": "Vyplňte atributy účtu. Hodnoty mohou být předvyplněny navrhovanými hodnotami. Pokud je to dovoleno, hodnoty mohou být ručně upraveny.",
After discussion this message is ok

2022-10-20 10:22 UTC, kucera-roman commented on Realization/frontend/czechidm-acc/src/locales/en.json
> +          "help": "Fill attributes for account. Values could be filled with suggested values. If it's allowed, you can change them manually.",
After discussion this message is ok

2022-11-02 07:42 UTC, tomdoischer commented
Looks good to me!

2022-11-02 07:42 UTC, merged