Pstrunc/3156 role assignment UI
bcvsolutions/CzechIdMng pull request #289
Opened 2022-12-08 10:28 UTC by peter-strunc

https://redmine.czechidm.com/issues/3156

2022-12-09 07:52 UTC, tomdoischer requested changes
- Flyway scripts need some love. There are duplicates.
- Flyway scripts are not complete. ERROR: column "applicant" of relation "idm_role_request" does not exist
- Cannot assign role to a contract with error: Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "applicant_id" violates not-null constraint
- Role assignment is missing in the wizard for account creation. Not sure it is a part of this ticket but there is no other ticket for it.
 
I didn't get further.

2022-12-09 07:52 UTC, tomdoischer commented on Realization/backend/app/src/main/resources/application.properties
> +idm.pub.app.show.identityRole.table.columns=role, roleAttributes, environment, owner, contractPosition, validFrom, validTill, directRole, automaticRole, incompatibleRoles
This needs to be in the changelog and documentation and I'm very worried we will forget it. :laughing:

2022-12-09 07:52 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/components/advanced/Filter/FilterButtons.js
> +    console.log("wwww",useFilter)
Remove this pls.

2022-12-09 07:52 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RequestIdentityRoleTable.js
> +      //forceSearchParameters = forceSearchParameters.setFilter('ownerType', null);
Remove this commented-out code.

2022-12-09 07:52 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/content/requestrole/RoleConceptDetail.js
> +                          //helpBlock={this.i18n('entity.IdentityRole.identityContract.help')}
Should it be used or not?

2022-12-09 07:52 UTC, tomdoischer commented on Realization/frontend/czechidm-core/src/services/ComponentService.js
> +    console.log("uuuu applicantType", applicantType)
Remove this pls.

2022-12-14 09:34 UTC, peter-strunc commented on Realization/backend/app/src/main/resources/application.properties
> +idm.pub.app.show.identityRole.table.columns=role, roleAttributes, environment, owner, contractPosition, validFrom, validTill, directRole, automaticRole, incompatibleRoles
added mention of this to changelog

2022-12-15 08:42 UTC, tomdoischer requested changes
Mostly works quite well, excellent job.

Some issues.
- Cannot assign roles with bulk action on identities.
- On account detail, tab Roles, when clicking Request to change roles, a white screen appears.
- Info component for an account has a link that doesn't get to the account detail but account table.
![Screenshot from 2022-12-15 09-40-06](https://user-images.githubusercontent.com/47480305/207812965-d14f5ea4-48b1-4826-b4a5-788dd530ce49.png)

- Localization is strange in role request detail:
![Screenshot from 2022-12-15 09-35-59](https://user-images.githubusercontent.com/47480305/207812902-f0361eb5-2a71-4af0-b865-6f8a71221a98.png)

2023-01-03 09:44 UTC, tomdoischer approved these changes

2023-01-03 09:44 UTC, merged