3248, fixed an issue with role composisition removal
bcvsolutions/CzechIdMng pull request #339
Opened 2023-03-02 09:57 UTC by tomdoischer

https://redmine.czechidm.com/issues/3248

2023-03-15 21:13 UTC, peter-strunc requested changes
Looks good, working well. Only a few issues regarding javadoc. GJ!

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +	 * Get available bulk actions for account
```suggestion
	 * Get available bulk actions for role composition
```

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +	 * Process bulk action for accounts
```suggestion
	 * Process bulk action for role compositions
```

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +			value = "Process bulk action for account",
```suggestion
			value = "Process bulk action for role composition",
```

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +	 * Prevalidate bulk action for accounts
```suggestion
	 * Prevalidate bulk action for role compositions
```

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +			value = "Prevalidate bulk action for accounts",
```suggestion
			value = "Prevalidate bulk action for role compositions",
```

2023-03-15 21:13 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/rest/impl/IdmRoleCompositionController.java
> +			value = "Preprocess bulk action for accounts",
```suggestion
			value = "Preprocess bulk action for role compositions",
```

2023-03-16 06:23 UTC, tomdoischer commented
Javadoc in the rest controller updated, nice catch, thank you!

2023-03-17 06:27 UTC, merged