Doischer/3271 spring 2 2
bcvsolutions/CzechIdMng pull request #349
Opened 2023-03-15 07:42 UTC by tomdoischer

https://redmine.czechidm.com/issues/3271

2023-04-19 09:41 UTC, peter-strunc requested changes

2023-04-19 09:41 UTC, peter-strunc commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/flyway/AbstractFlywayConfiguration.java
> +			location = environment.getProperty(prefix + ".locations");
I dont really like this. Would you consider injecting Environment through constructor and perhaps wrapping it in a decorator that could look something like this?:

     class NonResolvingNestedPlaceholdersEnvironment extends AbstractEnvironment {
        
        private final Environment env;

        private MyEnv(Environment env) {
            super();
            this.env = env;
            setIgnoreUnresolvableNestedPlaceholders(true);
        }
    }

Then nested placeholders wont be resolved and exception should not be thrown. It is cleaner to do it this way.

2023-04-19 09:41 UTC, peter-strunc commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/swagger/AbstractSwaggerConfig.java
> +		List<Predicate<RequestHandler>> basePackagesPredicates = Arrays.asList(basePackages)
You could use Arrays.stream to avoid constructing new List here

2023-04-19 09:41 UTC, peter-strunc commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/swagger/AbstractSwaggerConfig.java
> +		Predicate<RequestHandler> apiPredicate = basePackagesPredicates.stream().reduce(Predicate::or).orElse(x -> false);
this is sooo cool :)

2023-04-19 09:41 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/model/repository/filter/DefaultFilterManager.java
> +				builders.getPluginFor(new FilterKey(filterBuilder.getEntityClass(), filterBuilder.getName())).orElse(null);
This may produce null pointer exception. I would consider handling it more gracefully, perhaps using ifPresent()? I have seen it in multiple places, so please consider this little change

2023-04-19 12:20 UTC, tomdoischer commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/swagger/AbstractSwaggerConfig.java
> +		Predicate<RequestHandler> apiPredicate = basePackagesPredicates.stream().reduce(Predicate::or).orElse(x -> false);
:heart:

2023-04-19 13:03 UTC, tomdoischer commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/config/flyway/AbstractFlywayConfiguration.java
> +			location = environment.getProperty(prefix + ".locations");
I was able to improve it by creating a custom resolver which is easier. But you pushed me in the right direction, thank you. :kissing:

2023-10-03 10:05 UTC, peter-strunc approved these changes

2023-10-04 07:24 UTC, merged