Feature/3266 scheduler tasks sort by trigger start time
bcvsolutions/CzechIdMng pull request #362
Opened 2023-03-29 05:22 UTC by raicotop

2023-04-04 19:17 UTC, peter-strunc requested changes
There seem to be a lot of whitespace changes. Try not to commit these next time. You can check out our CONTRIBUTING.md for more info about autoformatting setup and so on.

It otherwise works as expected. I would consider checking for dependent tasks with cycles.

2023-04-04 19:17 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/service/impl/DefaultSchedulerManager.java
> +	public Page<Task> findUpcomingTasks(TaskFilter filter, Pageable pageable) {
This whole method is really big and not easy to read. I suggest refactoring it into smaller pieces.

2023-04-04 19:17 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/service/impl/DefaultSchedulerManager.java
> +						if (trigger instanceof CronTaskTrigger) {
Try to avoid instanceof operator by using polymorphism, or double dispatch pattern

2023-04-04 19:17 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/service/impl/DefaultSchedulerManager.java
> +					.filter(task -> !task.getTriggers().stream().allMatch(trigger -> trigger instanceof DependentTaskTrigger))
This instanceof could also be avoided

2023-04-06 05:37 UTC, raicotop commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/rest/impl/UpcomingTasksController.java
> +	@Autowired
For the constant? What would it be good for?

2023-04-06 05:59 UTC, raicotop commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/rest/impl/UpcomingTasksController.java
> +		if (parameterConverter == null) {
I just copied a solution from elsewhere. But looking at it I'm not sure if it can be initialized in the constructor since it depends on `lookupService` being autowired.

2023-04-06 06:25 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/rest/impl/UpcomingTasksController.java
> +	@Autowired
For autowired fileds

2023-04-12 13:39 UTC, peter-strunc commented on Realization/backend/core/core-impl/src/main/java/eu/bcvsolutions/idm/core/scheduler/service/impl/DefaultSchedulerManager.java
> +	public Page<Task> findUpcomingTasks(TaskFilter filter, Pageable pageable) {
after moving part of the algorithm to separate class it now looks plausible

2023-04-12 13:41 UTC, merged