Jkoula/3349 tech account password management
bcvsolutions/CzechIdMng pull request #413
Opened 2023-10-15 11:49 UTC by jkoula

2023-10-19 20:47 UTC, peter-strunc requested changes
Nice job, just a few minor changes needed and we should discuss whether we need to store account password in IdM.

2023-10-19 20:47 UTC, peter-strunc commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountService.java
> +					if (success || failure) {
What does it mean when the result is neither success nor failure? Please add a comment clarifying this a bit.

2023-10-19 20:47 UTC, peter-strunc commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccPasswordService.java
> +		password.setPassword(this.generateHash(newPassword, getSalt()));
We should discuss this a bit with someone regarding security. I get that the password itself is stored in IdM because of history and audit, but it may not be always wanted because it adds another place, where the password may be breached.

2023-10-19 20:47 UTC, peter-strunc commented on Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccPasswordServiceIntegrationTest.java
> +	@Test
Why are these commented out?

2023-10-19 20:47 UTC, peter-strunc commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/dto/filter/AbstractPasswordHistoryFilter.java
> +    private ZonedDateTime till;
Unify indentation please

2023-10-19 20:47 UTC, peter-strunc commented on Realization/frontend/czechidm-core/src/services/AbstractService.js
> +    console.log('getPermissions', id, this.getApiPath);
Remove this

2023-10-23 09:10 UTC, jkoula commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/dto/AccPasswordDto.java
> +    private UUID account;
done

2023-10-23 09:10 UTC, jkoula commented on Realization/backend/core/core-api/src/main/java/eu/bcvsolutions/idm/core/api/dto/filter/AbstractPasswordHistoryFilter.java
> +    private ZonedDateTime till;
done

2023-10-23 09:10 UTC, jkoula commented on Realization/frontend/czechidm-core/src/services/AbstractService.js
> +    console.log('getPermissions', id, this.getApiPath);
done

2023-10-23 22:08 UTC, jkoula commented on Realization/backend/acc/src/main/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccAccountService.java
> +					if (success || failure) {
It can't happen, added TODO for possilbe later condition removal.

2023-10-23 22:41 UTC, jkoula commented on Realization/backend/acc/src/test/java/eu/bcvsolutions/idm/acc/service/impl/DefaultAccPasswordServiceIntegrationTest.java
> +	@Test
Fixed.

2023-10-30 21:55 UTC, merged